-- MySQL Script generated by MySQL Workbench
-- Fri Apr 16 23:05:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema online_book_shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema online_book_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `online_book_shop_2` DEFAULT CHARACTER SET utf8 ;
USE `online_book_shop_2` ;

-- -----------------------------------------------------
-- Table `online_book_shop`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_book_shop`.`book` ;

CREATE TABLE IF NOT EXISTS `online_book_shop`.`book` (
  `ISBN` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `author` VARCHAR(255) NOT NULL,
  `publisher` VARCHAR(45) NOT NULL,
  `language` VARCHAR(45) NOT NULL,
  `stock` INT NULL,
  `price` DECIMAL(10,2) NULL,
  PRIMARY KEY (`ISBN`),
  UNIQUE INDEX `ISBN_UNIQUE` (`ISBN` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_book_shop`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_book_shop`.`customer` ;

CREATE TABLE IF NOT EXISTS `online_book_shop`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NOT NULL,
  `sname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `email` NVARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_book_shop`.`delivery_company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_book_shop`.`delivery_company` ;

CREATE TABLE IF NOT EXISTS `online_book_shop`.`delivery_company` (
  `reg_no` INT NOT NULL,
  `reg_date` DATETIME NOT NULL,
  `contract_due` DATETIME NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`reg_no`),
  UNIQUE INDEX `reg_num_UNIQUE` (`reg_no` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_book_shop`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_book_shop`.`address` ;

CREATE TABLE IF NOT EXISTS `online_book_shop`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address1` VARCHAR(45) NOT NULL,
  `address2` VARCHAR(45) NULL,
  `address3` VARCHAR(45) NULL,
  `city` VARCHAR(45) NOT NULL,
  `county` VARCHAR(45) NOT NULL,
  `postcode` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_book_shop`.`customer_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_book_shop`.`customer_address` ;

CREATE TABLE IF NOT EXISTS `online_book_shop`.`customer_address` (
  `customer_id` INT NULL,
  `address_id` INT NULL,
  INDEX `id_idx` (`address_id` ASC) ,
  INDEX `id_idx1` (`customer_id` ASC) ,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `online_book_shop`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `address_id`
    FOREIGN KEY (`address_id`)
    REFERENCES `online_book_shop`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_book_shop`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_book_shop`.`order` ;

CREATE TABLE IF NOT EXISTS `online_book_shop`.`order` (
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `cust_id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `addr_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`cust_id` ASC) ,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `id_idx1` (`addr_id` ASC) ,
  CONSTRAINT `cust_id`
    FOREIGN KEY (`cust_id`)
    REFERENCES `online_book_shop`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `addr_id`
    FOREIGN KEY (`addr_id`)
    REFERENCES `online_book_shop`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_book_shop`.`order_book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_book_shop`.`order_book` ;

CREATE TABLE IF NOT EXISTS `online_book_shop`.`order_book` (
  `order_id` INT NOT NULL,
  `ISBN` INT NOT NULL,
  `quantity` INT NOT NULL,
  `discount` DECIMAL(10,2) NULL,
  `sale_price` DECIMAL(10,2) NULL,
  INDEX `id_idx` (`order_id` ASC),
  INDEX `ISBN_idx` (`ISBN` ASC),
  CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `online_book_shop`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `ISBN`
    FOREIGN KEY (`ISBN`)
    REFERENCES `online_book_shop`.`book` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_book_shop`.`order_delivery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_book_shop`.`order_delivery` ;

CREATE TABLE IF NOT EXISTS `online_book_shop`.`order_delivery` (
  `ord_id` INT NOT NULL,
  `delivery_reg` INT NOT NULL,
  `due_date` DATETIME NULL,
  `delivery_staff_no` INT NULL,
  INDEX `id_idx` (`ord_id` ASC),
  INDEX `company_reg_idx` (`delivery_reg` ASC),
  CONSTRAINT `ord_id`
    FOREIGN KEY (`ord_id`)
    REFERENCES `online_book_shop`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `delivery_reg`
    FOREIGN KEY (`delivery_reg`)
    REFERENCES `online_book_shop`.`delivery_company` (`reg_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
